// This file emulates the linker and creates the section as globals
// that are usually generated by a linker as defined in the linker script.
// Linker script section variables will be emited to LLVM-IR by this file.
// This code is specific to Zephyr-RTOS.
// This file emulates linker scripts found in the files:
// - include/zephyr/linker/common-rom/common-rom-kernel-devices.ld
// - include/zephyr/arch/posix/native_tasks.ld
// - include/zephyr/sys/interate_sections.h
// - scripts/native_simulator/common/other/linker_script.pre.ld
// - etc.

#include <vector>
#include <list>
#include <map>
#include <llvm/ADT/StringRef.h>
#include <llvm/ExecutionEngine/GenericValue.h>
#include <llvm/IR/Constants.h>
#include <llvm/IR/LLVMContext.h>
#include <llvm/IR/Module.h>
#include <llvm/IR/Type.h>
#include <llvm/IR/GlobalVariable.h>
#include <llvm/IR/GlobalAlias.h>
#include <llvm/Support/raw_ostream.h>
#include <llvm/Support/Debug.h>
#include <llvm/Linker/Linker.h>
#include <llvm/IR/Verifier.h>

#define DEBUG_TYPE "IRXInterpreter::Sections"

using namespace llvm;

bool containsAndSplitFirst(StringRef &section, StringRef needle);
bool startsWithAndRemove(StringRef &section, StringRef prefix);

// Guard to temporarily mutate a values type
class MutateTypeGuard {
    Value *value;
    Type *savedTy;
public:
    MutateTypeGuard(Value *value, Type *mutateTy): value(value) {
        savedTy = value->getType();
        value->mutateType(mutateTy);
    }
    
    ~MutateTypeGuard() {
        value->mutateType(savedTy);
    }
};

struct SectionTypeConfig {
    const char* sectionName;
    const char* object;
    std::list<const char*> match_list;
    std::list<const char*> INITLIST;
    const char* startPrefix;
    const char* startPostfix;
    const char* endPrefix;
    const char* endPostfix;
    const char* namePrefix;
    const char* namePostfix;
};

struct SectionTypeConfig configs[] = {
    {
        "native_pre_tasks",
        nullptr,
        {".native_"},
        {
            "PRE_BOOT_1",
            "PRE_BOOT_2",
            "PRE_BOOT_3",
            "FIRST_SLEEP",
            "ON_EXIT",
        },
        "__native",
        "_tasks_start",
        "__native",
        "_tasks_end",
        "__native_",
        "_tasks_start",
    },
    {
        "nsi_tasks",
        nullptr,
        {".nsi_"},
        {
            "PRE_BOOT_1",
            "PRE_BOOT_2",
            "HW_INIT",
            "PRE_BOOT_3",
            "FIRST_SLEEP",
            "ON_EXIT_PRE",
            "ON_EXIT_POST",
        },
        "__nsi",
        "_tasks_start",
        "__nsi",
        "_tasks_end",
        "__nsi_",
        "_tasks_start",
    },
    {
        "nsi_hw_events",
        nullptr,
        {".nsi_"},
        {
            "hw_event",
        },
        "__nsi_hw_events",
        "_start",
        "__nsi_hw_events",
        "_end",
        "__nsi_unused_",
        "_unused",
    },
    {
        "initlevel",
        "init",
        {".z_init_"}, // object = "init"
        {
            "EARLY",
            "PRE_KERNEL_1",
            "PRE_KERNEL_2",
            "POST_KERNEL",
            "APPLICATION",
            "SMP",
        },
        "",
        "__init_start",
        "",
        "__init_end",
        "__init_", // todo replace "init" with object
        "_start",
    },
};

bool startsWithAndRemove(StringRef &section, StringRef prefix) {
    if(section.startswith(prefix)) {
        size_t len = std::string(prefix).length();
        section = section.substr(len);
        return true;
    }
    
    return false;
}

bool containsAndSplitFirst(StringRef &section, StringRef needle) {
    size_t n;
    if ((n = section.find(needle)) != std::string::npos) {
        section = section.substr(0, n);
        return true;
    }
    
    return false;
}

class SectionFinder {
protected:
    SectionTypeConfig *conf;
    std::list<std::string> list;
    
public:

    SectionFinder(SectionTypeConfig *conf) {
        this->conf = conf;
        std::copy(conf->INITLIST.begin(), conf->INITLIST.end(), std::back_inserter(list));
    }
    
    virtual bool test(StringRef &sec) {
        for(auto s : conf->match_list) {
            if(startsWithAndRemove(sec, s)) {
                return true;
            }
        }
        return false;
    }
    
    virtual std::list<std::string> levels() {
        return list;
    }
    
    virtual std::string section() {
        return conf->sectionName;
    }
    
    virtual bool hasLevel(StringRef sec) {
        for(auto &init : list) {
            if(startsWithAndRemove(sec, init)) {
                return true;
            }
        }
        return false;
    }
    
    virtual std::string level(StringRef sec) {
        for(auto &init : list) {
            if(startsWithAndRemove(sec, init)) {
                return init;
            }
        }
        
        throw std::invalid_argument("init level '" + sec.str() + "' name not found");
    }
    
    virtual std::string name(StringRef sec) {
        for(auto &init : list) {
            if(startsWithAndRemove(sec, init)) {
                sec = init;
                return conf->namePrefix + sec.str() + conf->namePostfix;
            }
        }
        
        throw std::invalid_argument("init level '" + sec.str() + "' name not found");
    }
    
    virtual std::string start(StringRef sec) {
        return std::string(conf->startPrefix) + sec.str() + conf->startPostfix;
    }
    
    virtual std::string end(StringRef sec) {
        return std::string(conf->endPrefix) + sec.str() + conf->endPostfix;
    }
    
    virtual void push_level(std::string level) {
        if(std::find(list.begin(), list.end(), level) == list.end()) {
            list.push_back(level);
        }
    }
    
    virtual Type* getType(Module *MG, Type *Ty, std::string _sec) {
        Type *GVTy = nullptr;

        // using its global name to get its type
        GlobalVariable *TGV = MG->getNamedGlobal(start(""));
        
        if(!TGV) {
            TGV = MG->getNamedGlobal(end(""));
        }
        
        if(TGV) {
            GVTy = TGV->getValueType();
            // arrays start pointer (type itself may be an array)
            if(GVTy->isArrayTy()) {
                GVTy = GVTy->getArrayElementType();
            }
        }
        
        // if type is still unknown, try to get the type from its elements
        // there is no guarantee that the elements will match the section GV array type
        if(!GVTy) {
            // already got the type from one of its elements that is beeing collected to an array.
            GVTy = Ty;
        }
        
        if(!GVTy) {
            // at this point the type probably does not matter
            // as it is not beeing used in the code. so any type would do.
            GVTy = getDefaultType(MG);
            
            LLVM_DEBUG(dbgs() << "Fallback to default type in section: " << _sec << " " << end("") << "\n");
        }
        
        return GVTy;
    }
    
    virtual Type* getDefaultType(Module *MG) {
        // use an int8 (void) pointer
        Type *VoidTy = Type::getInt8Ty(MG->getContext());
        return PointerType::get(VoidTy, 0);
    }
};

class ZephyrNativeSection : public SectionFinder {
public:
    ZephyrNativeSection(SectionTypeConfig *conf) : SectionFinder(conf) {}
    
    virtual std::string start(StringRef sec) {
        return std::string(conf->startPrefix) + conf->startPostfix;
    }
    
    virtual std::string end(StringRef sec) {
        return std::string(conf->endPrefix) + conf->endPostfix;
    }
    
    virtual Type* getDefaultType(Module *MG) {
        // use a function pointer as usually found in this section
        std::vector<Type*> args;
        Type *Ty = FunctionType::get(Type::getVoidTy(MG->getContext()), args, false);
        return PointerType::get(Ty, 0);
    }
};

struct SectionTypeConfig zephyrStatic = {
    nullptr,
    nullptr,
    {},
    {},
    "",
    "_list_start",
    "",
    "_list_end",
    "",
    "_area",
};

class ZephyrStaticSection : public SectionFinder {
    std::string object;
public:
    ZephyrStaticSection(const char* object) : SectionFinder(&zephyrStatic), object(object) {}
    
    virtual bool test(StringRef &sec) {
        return startsWithAndRemove(sec, "._" + object) && containsAndSplitFirst(sec, ".static.");
    }
    
    virtual bool hasLevel(StringRef sec) {
        return true;
    }
    
    virtual std::string name(StringRef sec) {
        return sec.str() + conf->namePostfix;
    }
    
    virtual std::string level(StringRef sec) {
        return sec.str();
    }
    
    virtual std::string section() {
        return object + "_area";
    }
    
    virtual std::string start(StringRef sec) {
        return "_" + object + "_list_start";
    }
    
    virtual std::string end(StringRef sec) {
        return "_" + object + "_list_end";
    }
};

// #define ALIASES_DISABLE

// set up the symbols using GEP to reference the sections
void emitLinkerScriptGlobalsOffset(Module *ModuleT, Module *ModuleS, std::string section, std::vector<Constant*> values,
                                   GlobalValue *globalVariable, size_t offset1) {
    auto &Context = ModuleT->getContext();
    auto *PackedTy = globalVariable->getValueType();
    auto *Ty = PackedTy->getArrayElementType();
    auto SizeTy = IntegerType::getInt32Ty(Context);
    
    size_t offset[2] = {0, offset1};

    // special case: end of section. Semantically equal
    if(values.size() != 0 && offset[0] == 0 && offset[1] == values.size()) {
        // makes use of GEP inbounds feature
        // this is how LLVM would usually create a pointer to the end of an array
        // this just makes the intent clearer or else it looks like an array is accessed out of bounds
        offset[0] = 1;
        offset[1] = 0;
    }
    
    auto gepIndices = std::vector<Constant*> {
        ConstantInt::getIntegerValue(SizeTy, APInt(32, offset[0])),
        ConstantInt::getIntegerValue(SizeTy, APInt(32, offset[1])),
    };
    
    GlobalVariable *offsetGV = ModuleS->getNamedGlobal(section);
    if(offsetGV) {
#ifndef ALIASES_DISABLE
        GlobalAlias *GA = GlobalAlias::create(offsetGV ->getValueType(), 0, GlobalVariable::ExternalLinkage, section, ModuleT);
        
        Constant *aliassee = nullptr;
        
        if(offsetGV->getValueType() == Ty) {
            auto *packedTy = ArrayType::get(Ty, values.size());
            aliassee = ConstantExpr::getInBoundsGetElementPtr(packedTy, globalVariable, gepIndices);
        } else if(offsetGV->getValueType()->isArrayTy()) {
            auto *GEP = ConstantExpr::getInBoundsGetElementPtr(globalVariable->getValueType(), globalVariable, gepIndices);
            aliassee = ConstantExpr::getBitCast(GEP, offsetGV ->getType());
        }
        
        // in case we did include a bitcast (isArrayTy)
        // since the types are diffrent the assertion while replacing the variable will fail.
        // Therefore we will change the Alias GA to the required type.
        // Our globalVariable variable is an array type, but we want to set a alias to
        // the first element of that array therefore needing to change the type.
        // Semantically this should accomplisch the same result as if it was an array
        // since its aliase is an element in that array. GEP operations will be unchanged.
        {
            MutateTypeGuard _guard(aliassee, GA->getType());
            GA->setAliasee(aliassee);
            (void)_guard;
        }
        
        assert(GA->getAliasee() && "Aliasee was not set");
        
        if(offsetGV->getValueType() == GA->getValueType()) {
            offsetGV->replaceAllUsesWith(GA);
        } else {
            offsetGV->replaceNonMetadataUsesWith(GA);
        }
        
        GA->takeName(offsetGV);
        
        offsetGV->eraseFromParent();
#else
        offsetGV->setInitializer(llvm::Constant::getNullValue(offsetGV->getValueType()));
#endif
    }
}

// Emit a zephyr specific linker script variable
GlobalVariable* emitLinkerScriptGlobal(Module *Module, std::string section, Type *Ty, std::vector<Constant*> values) {
    auto *packedTy = ArrayType::get(Ty, values.size());
    auto *SectionGV = new GlobalVariable(*Module, packedTy, false, GlobalVariable::ExternalLinkage, nullptr, section);
    SectionGV->setDSOLocal(true);
    SectionGV->setConstant(true);
    
    std::vector<Constant*> castedValues;
    for(auto v : values) {
#ifndef ALIASES_DISABLE
        // Should not cast on structs, but there type matches anyway
        if(Ty != v->getType()) {
            // v->dump();
            // Ty->dump();
            // auto bitCast = ConstantExpr::getBitCast(v, Ty);
            // SectionGV->dump();
            // v->getType()->dump();
            // bitCast->dump();
            // castedValues.push_back(bitCast);
            // v->mutateType(Ty);
            // castedValues.push_back(v);
            errs() << "warning: Types do not match, skipping collecting" << "\n";
            castedValues.push_back(llvm::Constant::getNullValue(Ty));
        } else {
            castedValues.push_back(v);
        }
#else
    castedValues.push_back(llvm::Constant::getNullValue(Ty));
#endif
    }
    
    SectionGV->setInitializer(ConstantArray::get(packedTy, castedValues));
    
    return SectionGV;
}

std::list<SectionFinder *> InitializeZephyrSectionFinders(Module *Module) {
    std::list<SectionFinder *> zephyrSections;
    
    auto found = std::list<std::string> {
        // Mandatory section. These sections are required even if they are empty and not found
        "k_object_assignment",
        "k_p4wq_initparam",
        "_static_thread_data",
        "irq_alloc",
        "device",
        "_deferred_init",
        "k_heap",
    };
    
    // create the mandatory section finders
    for(auto &section : found) {
        zephyrSections.push_back(new ZephyrStaticSection(section.c_str()));
    }
    
    // prepare section-finders using match_all_static_sections to find all sections present in LLVM-IR
    ZephyrStaticSection match_all_static_sections("");
    for (auto &Global : Module->globals()) {
        StringRef section = Global.getSection();
        if (!section.empty()) {
            if(match_all_static_sections.test(section)) {
                if(std::find(found.begin(), found.end(), section) == found.end()) {
                    // create specific section-finder for found section in LLVM-IR
                    zephyrSections.push_back(new ZephyrStaticSection(section.str().c_str()));
                    found.push_back(section.str());
                }
            }
        }
    }
    
    for(auto &conf : configs) {
        zephyrSections.push_back(new ZephyrNativeSection(&conf));
    }
    
    return zephyrSections;
}

// TODO maybe : create function to only process the external variables (instead of "all possible variables" as now) for sections
// collectLinkerScriptSectionsForVariable(M, externalVariable)

Module* collectLinkerScriptSections(Module *M) {
    std::list<SectionFinder *> finders = InitializeZephyrSectionFinders(M);
    
    // Module *MG = new Module("linker-globals", M->getContext());
    Module *MG = M;
    // MG->setDataLayout(M->getDataLayout());
    
    // structure is used to group by LEVEL and implicity sort by section name
    std::map<std::string, std::map<std::string, GlobalVariable *>> GVs;
    
    for (auto &sectionType : finders) {
        // Collecting global variables with sections in a continious memory of element in an arrays that emulates
        // the collecting of elements to an array into a section as usually defined in a linker script.
        for (auto &Global : M->globals()) {
            StringRef section = Global.getSection();
            if (!section.empty()) {
                StringRef sec = section;
                
                if(sectionType->test(sec)) {
                    if(sectionType->hasLevel(sec)) {
                        GVs[sectionType->level(sec)][Global.getSection().str()] = &Global;
                        sectionType->push_level(sectionType->level(sec));
                    } else {
                        LLVM_DEBUG(errs() << "hasLevel: not found: " << section << "\n");
                    }
                }
            }
        }
        
        std::vector<Constant*> values;
        std::list<size_t> indices;
        Type *Ty = nullptr;
        for(auto &level : sectionType->levels()) {
            indices.push_back(values.size());
            
            for(auto &GV : GVs[level]) {
                if(Ty == nullptr) {
                    Ty = GV.second->getValueType();
                } else {
                    if(Ty != GV.second->getValueType()) {
                        // Ty->dump();
                        // GV.second->getValueType()->dump();
                        errs() << "Unhandeled Error: Missmatched types within a section!\n";
                        // assert(false);
                    }
                }
                
                values.push_back(GV.second->getInitializer());
            }
        }
        
        // dbgs() << "=========SECTION START: "  << sectionType->section() << "\n";
        
        Ty = sectionType->getType(M, Ty, "");
        
        assert(Ty && "Type must be known of collected elements of the section");
        
        // for(auto &level : sectionType->levels()) {
        //     dbgs() << "Levels in section: " << level << "\n";
        // }
        
        // create the linker symbols
        
        GlobalVariable *area = emitLinkerScriptGlobal(MG, sectionType->section(), Ty, values);
        
        if (!indices.empty()) {
            emitLinkerScriptGlobalsOffset(MG, M, sectionType->start(""), values, area, indices.front());
        }
        
        for(auto &level : sectionType->levels()) {
            if(!level.empty()) {
                emitLinkerScriptGlobalsOffset(MG, M, sectionType->name(level), values, area, indices.front());
            }
            indices.pop_front();
        }
        
        emitLinkerScriptGlobalsOffset(MG, M, sectionType->end(""), values, area, values.size()+1);
        
        GVs.clear();
        
        // dbgs() << "========SECTION END: "  << sectionType->section() << "\n";
    }
    
    // MG->print(outs(), nullptr);
    // Linker::linkModules(*M, std::unique_ptr<Module>(MG), Linker::Flags::OverrideFromSrc);
    // verifyModule(*M, &errs());
    // delete MG;
    
    return MG;
}
